apiVersion: apps/v1
kind: Deployment
metadata:
  name: server-deployment
spec:
  selector:
    matchLabels:
      app: server
  replicas: 1
  template:
    metadata:
      labels:
        app: server
    spec:
      containers:
        - name: server
          image: azalurg/node-api-todo:1.4.6
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 5000
          env:
            - name: MONGO_HOST
              valueFrom:
                configMapKeyRef:
                  name: configmap
                  key: MONGO_HOST
            - name: MONGO_PORT
              valueFrom:
                configMapKeyRef:
                  name: configmap
                  key: MONGO_PORT
            - name: MONGO_DATABASE
              valueFrom:
                configMapKeyRef:
                  name: configmap
                  key: MONGO_DATABASE
            - name: REDIS_HOST
              valueFrom:
                configMapKeyRef:
                  name: configmap
                  key: REDIS_HOST
            - name: REDIS_PORT
              valueFrom:
                configMapKeyRef:
                  name: configmap
                  key: REDIS_PORT
            - name: API_PORT
              valueFrom:
                configMapKeyRef:
                  name: configmap
                  key: API_PORT
                  
---

apiVersion: v1
kind: Service
metadata:
  name: server-service-clusterip
spec:
  selector:
    app: server
  ports:
    - port: 5000
      targetPort: 5000
  type: ClusterIP
